name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
      if: success() && github.ref == 'refs/heads/master'
    - run: yarn test
      if: success() && github.ref == 'refs/heads/master'
      env:
        CI: true
    - run: yarn build
      if: success() && github.ref == 'refs/heads/master'
    - uses: peaceiris/actions-gh-pages@v3
      if: success() && github.ref == 'refs/heads/master'
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: gh-pages
        publish_dir: ./dist
